// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TodoListItems.Domain.Models;

[Table("TODO_Item")]
public partial class TODO_Item
{
    [Key]
    public int IdItem { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string Title { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    public int IdStatus { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [ForeignKey("IdStatus")]
    [InverseProperty("TODO_Items")]
    public virtual TODO_ItemStatus IdStatusNavigation { get; set; }
}