// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TodoListItems.Domain.Models;

public partial class TODO_LISTContext : DbContext
{
    public TODO_LISTContext(DbContextOptions<TODO_LISTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TODO_Item> TODO_Items { get; set; }

    public virtual DbSet<TODO_ItemStatus> TODO_ItemStatuses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TODO_Item>(entity =>
        {
            entity.HasKey(e => e.IdItem).HasName("PK__TODO_Ite__51E8426205C7DFA4");

            entity.HasOne(d => d.IdStatusNavigation).WithMany(p => p.TODO_Items)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TODO_Item_TODO_ItemStatus");
        });

        modelBuilder.Entity<TODO_ItemStatus>(entity =>
        {
            entity.Property(e => e.IdStatus).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}