// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TodoListItems.Domain.Models;

[Table("TODO_ItemStatus", Schema = "enum")]
public partial class TODO_ItemStatus
{
    [Key]
    public int IdStatus { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string Label { get; set; }
}